server:
  port: 8081

acho:
  client:
    host: 127.0.0.1
    port: 8080
    server-url: http://127.0.0.1:8080/acho # 注册中心地址
    fetch-interval-seconds: 30 # 自动拉取服务信息的时间间隔 s
    heart-interval-seconds: 3 # 心跳的时间间隔 s
    deadline-seconds: 9 # 存活时间 s
  instance:
    application:
      name: acho-client
